### ISSUE TITLE
Not properly skipping over svgs

### ISSUE THREAD

**Issue by jessieay** [18F/pa11y-crawl#4]
pa11y-crawl seems to skip over some svg files, but for others it seems to get confused:

```
 |->  analyzing localhost:3000/assets/shield-c90ba1cae13b734ac5bfef769ab974659a51a7184c9259b7592e0260fe22cd50.svg
Test function errored for "http://localhost:3000/assets/shield-c90ba1cae13b734ac5bfef769ab974659a51a7184c9259b7592e0260fe22cd50.svg"
Error: HTML CodeSniffer: undefined is not an object (evaluating 'f.nodeType')
    at Object.<anonymous> (/usr/local/lib/node_modules/pa11y/lib/pa11y.js:63:16)
    at Object.f [as onCallback] (/usr/local/lib/node_modules/pa11y/node_modules/once/once.js:17:25)
    at /usr/local/lib/node_modules/pa11y/node_modules/truffler/node_modules/node-phantom-simple/node-phantom-simple.js:636:30
    at Array.forEach (native)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/pa11y/node_modules/truffler/node_modules/node-phantom-simple/node-phantom-simple.js:617:17)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
jq: error (at /Users/jessicayoung/dev/identity-idp/pa11y-crawl/pa11y.json:0): Cannot use null (null) as object key
```

**Comment by stvnrlly** [comment]
If you're still seeing this error, can you tell what the MIME type of that file is?
